const initialobject = {
  avatar_url: "",
  bio: "",
  blog: "",
  company: "",
  created_at: "",
  email: "",
  events_url: "",
  followers: 0,
  following: 0,
  followers_url: "",
  following_url: "",
  gists_url: "",
  gravatar_id: "",
  hireable: "",
  html_url: "",
  id: 0,
  location: "",
  login: "",
  name: "",
  node_id: "",
  url: "",
  starred_url: "",
  subscriptions_url: "",
  organizations_url: "",
  repos_url: "",
  public_gists: 0,
  public_repos: 0,
  received_events_url: "",
  twitter_username: "",
  type: "",
  updated_at: "",
  site_admin: false,
};

export default initialobject;
